import { DocumentRow, UploadQueueItem, RecentUpload, ActivityItem } from "@/types";

export const documentRows: DocumentRow[] = [
  {
    id: "d-1",
    name: "Pump Manual - Model X200.pdf",
    type: "Manual",
    equipment: "Pump-23",
    department: "Maintenance",
    version: "v2.4",
    updatedAt: "2h ago",
    status: "Indexed",
    owner: "R. Fernandez",
    fileSize: "4.2 MB",
    summary: "Manufacturer manual covering installation, operating pressure ranges, and bearing maintenance schedules for the X200 pump series.",
    relatedEquipment: ["Pump-21", "Pump-22", "Pump-23"],
    relatedDocs: ["Maintenance Log - June.csv", "Inspection Report Q2.pdf"],
    aiInsights: ["Bearing wear identified as recurring issue.", "Pressure fluctuations exceed recommended threshold."],
    recommendedAction: "Schedule bearing inspection within the next maintenance cycle and verify operating pressure before restarting the asset.",
  },
  {
    id: "d-2",
    name: "Boiler Shutdown SOP.pdf",
    type: "SOP",
    equipment: "Boiler-11",
    department: "Operations",
    version: "v3.1",
    updatedAt: "2d ago",
    status: "Indexed",
    owner: "T. Nguyen",
    fileSize: "1.1 MB",
    summary: "Standard operating procedure for staged pressure release and cooldown sequence prior to any maintenance access.",
    relatedEquipment: ["Boiler-11"],
    relatedDocs: ["Furnace Shutdown SOP.pdf"],
    aiInsights: ["Cooldown period frequently skipped in incident logs."],
    recommendedAction: "Reinforce cooldown compliance training for shift operators.",
  },
  {
    id: "d-3",
    name: "Conveyor Maintenance Checklist.pdf",
    type: "Log",
    equipment: "Conveyor-08",
    department: "Maintenance",
    version: "v1.5",
    updatedAt: "6h ago",
    status: "Indexed",
    owner: "M. Osei",
    fileSize: "820 KB",
    summary: "Routine checklist for belt tension, alignment, and motor temperature checks on Line 3 conveyors.",
    relatedEquipment: ["Conveyor-08"],
    relatedDocs: ["Incident Report - Line 3.pdf"],
    aiInsights: ["Belt misalignment reported twice in past year."],
    recommendedAction: "Inspect belt tensioning system and standardize alignment check interval.",
  },
  {
    id: "d-4",
    name: "Turbine Inspection Report Q2.pdf",
    type: "Inspection",
    equipment: "Turbine-04",
    department: "Engineering",
    version: "v1.8",
    updatedAt: "5h ago",
    status: "Review Required",
    owner: "A. Costa",
    fileSize: "3.6 MB",
    summary: "Quarterly inspection findings noting elevated vibration readings and a recommended thermal imaging follow-up.",
    relatedEquipment: ["Turbine-04"],
    relatedDocs: ["Turbine-04 Overheating Alert"],
    aiInsights: ["Vibration readings 12% above baseline.", "Thermal follow-up not yet scheduled."],
    recommendedAction: "Schedule thermal imaging inspection before next operating cycle.",
  },
  {
    id: "d-5",
    name: "Compressor Service History.xlsx",
    type: "Log",
    equipment: "Compressor-5",
    department: "Maintenance",
    version: "v1.0",
    updatedAt: "3d ago",
    status: "Indexed",
    owner: "R. Fernandez",
    fileSize: "540 KB",
    summary: "Full service and part-replacement history for Compressor-5 dating back 18 months.",
    relatedEquipment: ["Compressor-5"],
    relatedDocs: [],
    aiInsights: ["No anomalies detected in recent service intervals."],
    recommendedAction: "No immediate action required — continue standard service interval.",
  },
  {
    id: "d-6",
    name: "Incident Report - Line 3.pdf",
    type: "Incident",
    equipment: "Conveyor-08",
    department: "Safety",
    version: "v1.2",
    updatedAt: "1d ago",
    status: "Processing",
    owner: "S. Ibrahim",
    fileSize: "1.8 MB",
    summary: "Documented belt misalignment incident causing a 40-minute production stoppage on Line 3.",
    relatedEquipment: ["Conveyor-08"],
    relatedDocs: ["Conveyor Maintenance Checklist.pdf"],
    aiInsights: ["Similar incident detected in March."],
    recommendedAction: "Cross-reference March incident report and verify root cause consistency.",
  },
  {
    id: "d-7",
    name: "Pressure Test Results.csv",
    type: "Technical Specification",
    equipment: "Pump-23",
    department: "Engineering",
    version: "v1.0",
    updatedAt: "4d ago",
    status: "Indexed",
    owner: "A. Costa",
    fileSize: "210 KB",
    summary: "Raw pressure test data across five operating cycles for Pump-23 recalibration validation.",
    relatedEquipment: ["Pump-23"],
    relatedDocs: ["Pump Manual - Model X200.pdf"],
    aiInsights: ["Pressure variance within tolerance across all cycles."],
    recommendedAction: "Archive as reference for next recalibration cycle.",
  },
  {
    id: "d-8",
    name: "Engineering Specification Rev-C.pdf",
    type: "Engineering Drawing",
    equipment: "Furnace-02",
    department: "Engineering",
    version: "Rev-C",
    updatedAt: "1w ago",
    status: "Archived",
    owner: "T. Nguyen",
    fileSize: "6.4 MB",
    summary: "Revision C engineering drawings for Furnace-02 refractory lining and thermal ramp specifications.",
    relatedEquipment: ["Furnace-02"],
    relatedDocs: ["Boiler Shutdown SOP.pdf"],
    aiInsights: ["Superseded by Rev-D — pending upload."],
    recommendedAction: "Upload Rev-D once available and mark this version fully archived.",
  },
  {
    id: "d-9",
    name: "Work Order WO-2026-018.pdf",
    type: "Work Order",
    equipment: "Motor-14",
    department: "Maintenance",
    version: "v1.0",
    updatedAt: "8h ago",
    status: "Processing",
    owner: "M. Osei",
    fileSize: "310 KB",
    summary: "Active work order for bearing replacement on Motor-14, scheduled for the next maintenance window.",
    relatedEquipment: ["Motor-14"],
    relatedDocs: ["Inspection Report Q2.pdf"],
    aiInsights: ["Parts availability confirmed."],
    recommendedAction: "Confirm technician assignment before scheduled window.",
  },
  {
    id: "d-10",
    name: "Safety Inspection Checklist.pdf",
    type: "Inspection",
    equipment: "Furnace-02",
    department: "Safety",
    version: "v2.0",
    updatedAt: "12h ago",
    status: "Indexed",
    owner: "S. Ibrahim",
    fileSize: "670 KB",
    summary: "Monthly safety inspection covering emergency shutoffs, ventilation, and thermal barrier integrity.",
    relatedEquipment: ["Furnace-02"],
    relatedDocs: ["Engineering Specification Rev-C.pdf"],
    aiInsights: ["All emergency shutoffs verified functional."],
    recommendedAction: "No action required — next inspection due in 30 days.",
  },
];

export const uploadQueue: UploadQueueItem[] = [
  { id: "u-1", name: "Pump Manual.pdf", fileType: "PDF", progress: 100, status: "Indexed" },
  { id: "u-2", name: "Shutdown SOP.pdf", fileType: "PDF", progress: 82, status: "Processing" },
  { id: "u-3", name: "Maintenance Log.csv", fileType: "CSV", progress: 45, status: "Uploading" },
];

export const recentUploads: RecentUpload[] = [
  { id: "r-1", name: "Pump Manual.pdf", equipment: "Pump-23", department: "Maintenance", uploadedBy: "Admin", time: "2 mins ago", status: "Indexed" },
  { id: "r-2", name: "Inspection Q2.pdf", equipment: "Turbine-04", department: "Engineering", uploadedBy: "Sarah", time: "15 mins ago", status: "Processing" },
  { id: "r-3", name: "Compressor Log.xlsx", equipment: "Compressor-5", department: "Maintenance", uploadedBy: "Admin", time: "42 mins ago", status: "Indexed" },
  { id: "r-4", name: "Safety Checklist.pdf", equipment: "Furnace-02", department: "Safety", uploadedBy: "R. Fernandez", time: "1h ago", status: "Failed" },
];

export const uploadActivity: ActivityItem[] = [
  { id: "a-1", message: "Pump Manual.pdf indexed successfully", time: "2 minutes ago", status: "Indexed" },
  { id: "a-2", message: "Inspection Report uploaded", time: "15 minutes ago", status: "Processing" },
  { id: "a-3", message: "Maintenance Log failed validation", time: "30 minutes ago", status: "Failed" },
  { id: "a-4", message: "Shutdown SOP indexed", time: "1 hour ago", status: "Indexed" },
];
